-- [MC]Constants from the game so I don't have to look them up on the steam guide.

-- Unit Commands
CMD_NONE =					0;
CMD_SELECT =				1;
CMD_STOP =					2;
CMD_GO =					3;
CMD_ATTACK =				4;
CMD_FOLLOW =				5;
CMD_FORMATION =				6;
CMD_PICKUP =				7;
CMD_DROPOFF =				8;
CMD_UNDEPLOY =				9;
CMD_DEPLOY =				10;
CMD_NO_DEPLOY =				11;
CMD_GET_REPAIR =			12;
CMD_GET_RELOAD =			13;
CMD_GET_WEAPON =			14;
CMD_GET_CAMERA =			15;
CMD_GET_BOMB =				16;
CMD_DEFEND =				17;
CMD_RESCUE =				18;
CMD_RECYCLE =				19;
CMD_SCAVENGE =				20;
CMD_HUNT =					21;
CMD_BUILD =					22;
CMD_PATROL =				23;
CMD_STAGE =					24;
CMD_SEND =					25;
CMD_GET_IN =				26;
CMD_LAY_MINES =				27;
CMD_LOOK_AT =				28;
CMD_SERVICE =				29;
CMD_UPGRADE =				30;
CMD_DEMOLISH =				31;
CMD_POWER =					32;
CMD_BACK =					33;
CMD_DONE =					34;
CMD_CANCEL =				35;
CMD_SET_GROUP =				36;
CMD_SET_TEAM =				37;
CMD_SEND_GROUP =			38;
CMD_TARGET =				39;
CMD_INSPECT =				40;
CMD_SWITCHTEAM =			41;
CMD_INTERFACE = 			42;
CMD_LOGOFF = 				43;
CMD_AUTOPILOT = 			44;
CMD_MESSAGE = 				45;
CMD_CLOSE = 				46;
CMD_MORPH_SETDEPLOYED =		47;
CMD_MORPH_SETUNDEPLOYED =	48;
CMD_MORPH_UNLOCK =			49;
CMD_BAILOUT =				50;
CMD_BUILD_ROTATE =			51;
CMD_CMDPANEL_SELECT =		52;
CMD_CMDPANEL_DESELECT =		53;

-- Entity Types via GetClassSig()
CID_NONE = 			"CLASS_ID_NONE" 		-- undefined object (default)
CID_CRAFT = 		"CLASS_ID_CRAFT" 		-- hovering vehicle
CID_VEHICLE = 		"CLASS_ID_VEHICLE" 		-- tracked vehicle
CID_TORPEDO = 		"CLASS_ID_TORPEDO" 		-- miniature vehicle
CID_POWERUP = 		"CLASS_ID_POWERUP" 		-- power up pod
CID_PERSON = 		"CLASS_ID_PERSON" 		-- pilot or soldier
CID_ANIMAL = 		"CLASS_ID_ANIMAL" 		-- animal
CID_STRUCT = 		"CLASS_ID_STRUCT" 		-- generic building
CID_BUILDING = 		"CLASS_ID_BUILDING" 	-- important building
CID_SIGN = 			"CLASS_ID_SIGN" 		-- mine object
CID_SCRAP = 		"CLASS_ID_SCRAP" 		-- scrap piece
CID_DEPOSIT = 		"CLASS_ID_DEPOSIT" 		-- scrap deposit
CID_BEACON = 		"CLASS_ID_BEACON" 		-- nav beacon
CID_PLANT = 		"CLASS_ID_PLANT" 		-- plant object
CID_TERRAIN = 		"CLASS_ID_TERRAIN" 		-- terrain object
CID_WEAPON = 		"CLASS_ID_WEAPON" 		-- weapon object
CID_ORDNANCE = 		"CLASS_ID_ORDNANCE" 	-- ordnance object
CID_EXPLOSION = 	"CLASS_ID_EXPLOSION" 	-- explosion object
CID_CHUNK = 		"CLASS_ID_CHUNK" 		-- chunk object
CID_CRASH = 		"CLASS_ID_CRASH" 		-- crash object
CID_COLLAPSE = 		"CLASS_ID_COLLAPSE" 	-- collapsing object

-- classLabel bases via GetClassLabel
CLS_AIR = 					"CLASS_AIR" -- AirCraft.h
CLS_ANCHORROCKET = 			"CLASS_ANCHORROCKET" -- AnchorRocketClass.h
CLS_APC = 					"CLASS_APC" -- APC.h
CLS_ARCCANNON = 			"CLASS_ARCCANNON" -- ArcCannonClass.h
CLS_ARMORY = 				"CLASS_ARMORY" -- Armory.h
CLS_ARTIFACT = 				"CLASS_ARTIFACT" -- Artifact.h
CLS_ARTILLERY = 			"CLASS_ARTILLERY" -- Artillery.h
CLS_ASSAULTTANK = 			"CLASS_ASSAULTTANK" -- AssaultTank.h
CLS_ASSAULTHOVER = 			"CLASS_ASSAULTHOVER" -- AssaultHover.h
CLS_BARRACKS = 				"CLASS_BARRACKS" -- Barracks.h
CLS_BEAM = 					"CLASS_BEAM"
CLS_BLINK = 				"CLASS_BLINK" -- BlinkDeviceClass.h
CLS_BOID = 					"CLASS_BOID"
CLS_BOMBER = 				"CLASS_BOMBER" -- Bomber.h
CLS_BOMBERBAY = 			"CLASS_BOMBERBAY" -- BomberBay.h
CLS_BOUNCEBOMB = 			"CLASS_BOUNCEBOMB"
CLS_BUILDING = 				"CLASS_BUILDING" -- BuildingClass.h
CLS_BULLET = 				"CLASS_BULLET" -- BulletClass.h
CLS_CANNON = 				"CLASS_CANNON" -- CannonClass.h
CLS_CANNON_MACHINEGUN = 	"CLASS_CANNON_MACHINEGUN" -- MachineGunClass.h
CLS_CANNON_TARGETING = 		"CLASS_CANNON_TARGETING" -- TargetingGunClass.h
CLS_CHARGEGUN = 			"CLASS_CHARGEGUN" -- ChargeGunClass.h
CLS_COMMBUNKER = 			"CLASS_COMMBUNKER" -- CommBunker.h
CLS_COMMTOWER = 			"CLASS_COMMTOWER" -- CommTower.h
CLS_COMMVEHICLE = 			"CLASS_COMMVEHICLE" -- CommVehicle.h
CLS_CONSTRUCTIONRIG = 		"CLASS_CONSTRUCTIONRIG" -- ConstructionRig.h
CLS_CONSTRUCTIONRIGT = 		"CLASS_CONSTRUCTIONRIGT" -- ConstructionRigT.h
CLS_CRAFT = 				"CLASS_CRAFT" -- CraftClass.h
CLS_DAMAGEFIELD = 			"CLASS_DAMAGEFIELD" -- DamageFieldClass.h
CLS_DAYWRECKER = 			"CLASS_DAYWRECKER" -- DayWrecker.h
CLS_DEPLOYABLE = 			"CLASS_DEPLOYABLE" -- Deployable.h
CLS_DEPLOYBUILDING = 		"CLASS_DEPLOYBUILDING" -- DeployBuilding.h
CLS_DEPLOYBUILDINGH = 		"CLASS_DEPLOYBUILDINGH" -- DeployBuildingH.h
CLS_DEPOSIT = 				"CLASS_DEPOSIT" -- Deposit.h
CLS_DISPENSER = 			"CLASS_DISPENSER" -- DispenserClass.h
CLS_EXPLOSION = 			"CLASS_EXPLOSION" -- ExplosionClass.h
CLS_EXTRACTOR = 			"CLASS_EXTRACTOR" -- Extractor.h
CLS_FACTORY = 				"CLASS_FACTORY" -- Factory.h
CLS_FLAG = 					"CLASS_FLAG" -- FlagObject.h
CLS_FLAREMINE = 			"CLASS_FLAREMINE" -- FlareMineClass.h
CLS_GAMEOBJECT = 			"CLASS_GAMEOBJECT" -- GameObjectClass.h
CLS_GRENADE = 				"CLASS_GRENADE" -- GrenadeClass.h
CLS_GRENADE_LASERPOPPER =	"CLASS_GRENADE_LASERPOPPER" -- LaserPopperClass.h
CLS_GRENADE_POPPER = 		"CLASS_GRENADE_POPPER" -- PopperClass.h
-- "CLASS_GRENADE_RADARPOPPER" -- RadarPopperClass.h [Same sig as GRENADE_POPPER, uses that]
CLS_HOVER = 				"CLASS_HOVER" -- HoverCraft.h
CLS_HOWITZER = 				"CLASS_HOWITZER" -- Howitzer.h
CLS_I76BUILDING = 			"CLASS_I76BUILDING" -- Building.h
CLS_JAMMER = 				"CLASS_JAMMER" -- JammerTower.h
CLS_JETPACK = 				"CLASS_JETPACK" -- JetPackClass.h
CLS_KINGOFHILL = 			"CLASS_KINGOFHILL" -- KingOfHill.h
CLS_LAUNCHER = 				"CLASS_LAUNCHER" -- LauncherClass.h
CLS_LAUNCHER_IMAGE = 		"CLASS_LAUNCHER_IMAGE" -- ImageLauncherClass.h
CLS_LAUNCHER_MULTI = 		"CLASS_LAUNCHER_MULTI" -- MultiLauncherClass.h
CLS_LAUNCHER_RADAR = 		"CLASS_LAUNCHER_RADAR" -- RadarLauncherClass.h
CLS_LAUNCHER_THERMAL = 		"CLASS_LAUNCHER_THERMAL" -- ThermalLauncherClass.h
CLS_LAUNCHER_TORPEDO = 		"CLASS_LAUNCHER_TORPEDO" -- TorpedoLauncherClass.h
-- "CLASS_LEADER_ROUND" -- LeaderRoundClass.h [Same sig as CLASS_CANNON_TARGETING, returns that]
CLS_LOCKSHELL = 			"CLASS_LOCKSHELL" -- LockShellClass.h
CLS_MAGNETGUN = 			"CLASS_MAGNETGUN" -- MagnetGunClass.h
CLS_MAGNETSHELL = 			"CLASS_MAGNETSHELL" -- MagnetShellClass.h
CLS_MINE = 					"CLASS_MINE" -- MineClass.h
CLS_MINELAYER = 			"CLASS_MINELAYER" -- Minelayer.h
CLS_MINE_MAGNET = 			"CLASS_MINE_MAGNET" -- MagnetMineClass.h
CLS_MINE_PROXIMITY = 		"CLASS_MINE_PROXIMITY" -- ProximityMineClass.h
CLS_MINE_TRIP = 			"CLASS_MINE_TRIP" -- TripMineClass.h
CLS_MINE_WEAPON = 			"CLASS_MINE_WEAPON" -- WeaponMineClass.h
CLS_MISSILE = 				"CLASS_MISSILE" -- MissileClass.h
CLS_MISSILE_IMAGE = 		"CLASS_MISSILE_IMAGE" -- ImageMissileClass.h
CLS_MISSILE_LASER = 		"CLASS_MISSILE_LASER" -- LaserMissileClass.h
CLS_MISSILE_RADAR = 		"CLASS_MISSILE_RADAR" -- RadarMissileClass.h
CLS_MISSILE_THERMAL = 		"CLASS_MISSILE_THERMAL" -- ThermalMissileClass.h
CLS_MORPHTANK = 			"CLASS_MORPHTANK" -- MorphTank.h
CLS_MORTAR = 				"CLASS_MORTAR" -- MortarClass.h
CLS_MORTAR_REMOTE = 		"CLASS_MORTAR_REMOTE" -- RemoteDetonatorClass.h
CLS_MOTIONSENSOR = 			"CLASS_MOTIONSENSOR" -- MotionSensor.h
CLS_NAVBEACON = 			"CLASS_NAVBEACON" -- NavBeaconClass.h
CLS_OBJECTSPAWN = 			"CLASS_OBJECTSPAWN" -- ObjectSpawn.h
CLS_ORDNANCE = 				"CLASS_ORDNANCE" -- OrdnanceClass.h
CLS_PERSON = 				"CLASS_PERSON" -- PersonClass.h
CLS_PLANT = 				"CLASS_PLANT" -- Plant.h -- Power plants, not foliage plants. -GBD
CLS_POWERED = 				"CLASS_POWERED" -- PoweredBuilding.h
CLS_POWERUP_CAMERA = 		"CLASS_POWERUP_CAMERA" -- CameraPod.h
CLS_POWERUP_MONEY = 		"CLASS_POWERUP_MONEY" -- MoneyPowerup.h
CLS_POWERUP_RELOAD = 		"CLASS_POWERUP_RELOAD" -- ServicePowerup.h
CLS_POWERUP_REPAIR = 		"CLASS_POWERUP_REPAIR" -- ServicePowerup.h
CLS_POWERUP_SERVICE = 		"CLASS_POWERUP_SERVICE" -- ServicePowerup.h
-- "CLASS_POWERUP_WEAPON" -- WeaponPowerup.h [Same sig as CLASS_WEAPON, returns that]
CLS_PULSESHELL = 			"CLASS_PULSESHELL" -- PulseShellClass.h
CLS_RECYCLER = 				"CLASS_RECYCLER" -- Recycler.h
CLS_RECYCLERVEHICLE = 		"CLASS_RECYCLERVEHICLE" -- RecyclerVehicle.h
CLS_RECYCLERVEHICLEH = 		"CLASS_RECYCLERVEHICLEH" -- RecyclerVehicleH.h
CLS_SALVOLAUNCHER = 		"CLASS_SALVOLAUNCHER" -- SalvoLauncherClass.h
CLS_SATCHELCHARGE = 		"CLASS_SATCHELCHARGE" -- SatchelCharge.h
CLS_SATCHELPACK = 			"CLASS_SATCHELPACK" -- SatchelPackClass.h
CLS_SAV = 					"CLASS_SAV" -- SAV.h
CLS_SCAVENGER = 			"CLASS_SCAVENGER" -- Scavenger.h
CLS_SCAVENGERH = 			"CLASS_SCAVENGERH" -- ScavengerH.h
CLS_SCRAP = 				"CLASS_SCRAP" -- Scrap.h
CLS_SEEKER = 				"CLASS_SEEKER" -- SeekerClass.h
CLS_SEISMICWAVE = 			"CLASS_SEISMICWAVE" -- SeismicWaveClass.h
CLS_SERVICE = 				"CLASS_SERVICE" -- ServiceTruck.h
CLS_SERVICEH = 				"CLASS_SERVICEH" -- ServiceTruckH.h
CLS_SHIELDTOWER = 			"CLASS_SHIELDTOWER" -- ShieldTower.h
CLS_SHIELDUP = 				"CLASS_SHIELDUP" -- ShieldUpgradeClass.h
CLS_SIGN = 					"CLASS_SIGN" -- BuildingClass.h
CLS_SILO = 					"CLASS_SILO" -- Silo.h
CLS_SNIPERSHELL = 			"CLASS_SNIPERSHELL" -- SniperShellClass.h
CLS_SPAWNBUOY = 			"CLASS_SPAWNBUOY" -- SpawnBuoy.h
CLS_SPECIAL = 				"CLASS_SPECIAL" -- SpecialItemClass.h
CLS_SPECIAL_FORCEFIELD = 	"CLASS_SPECIAL_FORCEFIELD" -- ForceFieldClass.h
CLS_SPECIAL_IMAGEREFRACT = 	"CLASS_SPECIAL_IMAGEREFRACT" -- ImageRefractClass.h
CLS_SPECIAL_RADARDAMPER = 	"CLASS_SPECIAL_RADARDAMPER" -- RadarDamperClass.h
CLS_SPECIAL_TERRAINEXPOSE =	"CLASS_SPECIAL_TERRAINEXPOSE" -- TerrainExposeClass.h
CLS_SPRAYBOMB = 			"CLASS_SPRAYBOMB" -- SprayBombClass.h
CLS_SPRAYBUILDING = 		"CLASS_SPRAYBUILDING" -- SprayBuildingClass.h
CLS_SUPPLYDEPOT = 			"CLASS_SUPPLYDEPOT" -- SupplyDepot.h
CLS_TELEPORTAL = 			"CLASS_TELEPORTAL" -- TelePortalClass.h
CLS_TERRAIN = 				"CLASS_TERRAIN" -- DummyClass.h
CLS_TORPEDO = 				"CLASS_TORPEDO" -- TorpedoClass.h
CLS_TRACKEDDEPLOYABLE = 	"CLASS_TRACKEDDEPLOYABLE" -- TrackedDeployable.h
CLS_TRACKEDVEHICLE = 		"CLASS_TRACKEDVEHICLE" -- TrackedVehicle.h
CLS_TUG = 					"CLASS_TUG" -- Tug.h
CLS_TURRET = 				"CLASS_TURRET" -- TurretCraft.h - ibgtow/fbspir (Guntower/gunspires)
CLS_TURRETTANK = 			"CLASS_TURRETTANK" -- TurretTank.h - ivturr/fvturr (vehicle turrets)
CLS_WALKER = 				"CLASS_WALKER" -- Walker.h
CLS_WEAPON = 				"CLASS_WEAPON" -- WeaponClass.h
CLS_WINGMAN = 				"CLASS_WINGMAN" -- Wingman.h
CLS_UNKNOWN = 				"CLASS_UNKNOWN" -- default
